#!/usr/bin/env bash
#print "Best school" 10 times
#and also prints "Hi" at the ninth iteration

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
